name: Image Build and Push All

on:
  push:
    branches:
      - main

jobs:
    build:
        strategy:
            matrix:
                bw_version:
                    - "2024.4.1"
                    - "2024.3.1"
        uses: ./.github/workflows/image-build-push.yml
        with:
            version: ${{ matrix.bw_version }}
