name: Image Build and Push All

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                image:
                    - v2024.4.1
                    - v2024.3.1
        steps:
        - name: Build images
          uses: ./.github/workflows/image-build-push.yml
          with:
            version: ${{ matrix.image }}
