name: Image Build and Push All

on:
  push:
    branches:
      - main

jobs:
    build:
        permissions:
            packages: write
            contents: read
        strategy:
            matrix:
                bw_version:
                    - "2024.6.1"
                    - "2024.7.1"
        uses: ./.github/workflows/image-build-push.yml
        with:
            version: ${{ matrix.bw_version }}
