name: Image Build and Push All

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                image:
                    - "2024.4.1"
                    - "2024.3.1"
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Build images
            uses: ./.github/workflows/image-build-push.yml
            with:
                version: ${{ matrix.image }}
