name: Image Build and Push

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
    build:
      permissions:
        id-token: write
        contents: read
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }}
          build-args: |
            BW_VERSION=${{ github.event.inputs.version }}
